[package]
name = "security-cam-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nokhwa = "0.10.4"
reqwest = {version = "0.11.22", features = ["cookies"]}
security-cam-common = "0.1.2"
